version: '2'
services:
    jhipstermoj-app:
        image: jhipstermoj
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipstermoj-postgresql:5432/jhipstermoj
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipstermoj-postgresql:
        extends:
            file: postgresql.yml
            service: jhipstermoj-postgresql
