version: '2'
services:
    jhipstermoj-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/jhipstermoj/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipstermoj
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
